Add sensible check for latexmk and pdflatex

diff --git a/res/bin/compile b/res/bin/compile
--- a/res/bin/compile
+++ b/res/bin/compile
@@ -10,18 +10,19 @@ eof
 
 [ $# -eq 2 ] || usage
 
-if [ -x "/usr/bin/latexmk" ]; then
-    PREFIX=/usr/bin
-elif [ -x "/usr/texbin/latexmk" ]; then
-    PREFIX=/usr/texbin
-else
+LATEXMK=`which latexmk`
+PDFLATEX=`which pdflatex`
+if [ -z "$LATEXMK" ]; then
     echo 'latexmk not found' >&2
+    exit 1
+elif [ -z "$PDFLATEX" ]; then
+    echo 'pdflatex not found' >&2
     exit 1
 fi
 
 path="$1"
 src="$2"
 
-TEXINPUTS='res/document-classes/:' $PREFIX/latexmk -gg -pdf -pdflatex="$PREFIX/pdflatex -interaction=nonstopmode" -jobname=$path $src
+TEXINPUTS='res/document-classes/:' $LATEXMK -gg -pdf -pdflatex="$PDFLATEX -interaction=nonstopmode" -jobname=$path $src
 
 exit $?
